/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package us.schueler.cando.utilities

import us.schueler.cando.list.LinkedList

class StringUtils {
    static String join(LinkedList source) {
        return JoinUtils.join(source)
    }

    static LinkedList split(String source) {
        return SplitUtils.split(source)
    }
}
