/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package us.schueler.cando.app

import us.schueler.cando.list.LinkedList

import static us.schueler.cando.utilities.StringUtils.join
import static us.schueler.cando.utilities.StringUtils.split
import static us.schueler.cando.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
