# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish tag release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching semver 20.15.10

jobs:
  publish_artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build :app:build
      - name: Get Release Version
        id: get_version
        run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            --generate-notes \
            --title 'Release ${{ github.ref_name }}' \
            ${{ github.ref_name }} \
            ./app/build/distributions/how-${{ steps.get_version.outputs.VERSION }}.zip \
            ./app/build/libs/how-${{ steps.get_version.outputs.VERSION }}-all.jar
      - name: trigger homebrew update
        run: gh workflow run update_homebrew.yml
        env:
          GH_TOKEN: ${{ github.token }}
