name: Update homebrew repo

on: workflow_dispatch

jobs:
   update_homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: get download values
        id: download
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # get download values
          res=$(curl -s -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/rundeckpro/howto-cli-tool/releases/latest )
          echo "$res"

          url=$(jq -r '.assets[] |  select ( .name | test( "^how-.*-all.jar$") ) | .url' <<< "$res")
          name=$(jq -r '.assets[] |  select ( .name | test( "^how-.*-all.jar$") ) | .name' <<< "$res")
          version=$(echo $name | sed -E 's/.*-([0-9]\.[0-9]+\.[0-9]+).*/\1/')

          curl -f -s -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer $GH_TOKEN"  -L -o /tmp/tmp.file $url
          if [ $? != 0 ] ; then
            echo "Download failed for URL $url"
            exit 2
          fi
          sha=$(sha256sum /tmp/tmp.file | cut -d' ' -f1)
          echo "✅ Found version $version: sha $sha: $url" | tee -a $GITHUB_STEP_SUMMARY
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: trigger homebrew update
        # The PAT should have actions:read-write
        run: |
            curl -L \
            -X POST \
            --fail-with-body \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.HOMEBREW_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rundeckpro/homebrew-howto-cli-tool/actions/workflows/update.yml/dispatches \
            -d '{"ref":"main","inputs":{"version":"${{steps.download.outputs.version}}","sha":"${{steps.download.outputs.sha}}"}}'
